config/routes.rb
Pykture::Application.routes.draw do
  devise_for :users
  resources :users, :only => [:show] do
    member do
      get :following, :followers
    end
  end
  resources :pictures, :only => [:index, :destroy, :create]
  resources :followed
  resources :tags, :only => [:show]
  resources :votes, :only => [:create]
  root 'pictures#index'
  get '/index', to: 'pictures#index'
  get '/about', to: 'static_pages#about'
  get '/blog', to: 'static_pages#blog'
  get '/legal', to: 'static_pages#legal'
  get '/search', to: 'search#search'
  resources :relationships, only: [:create, :destroy]

end

app/views/shared/_follow.html.erb
<%= form_for(current_user.followed_items.build, :remote => true) do |f| %>
	<div><%= hidden_field_tag :followable_id, item.id %></div>
	<div><%= hidden_field_tag :followable_type, item.class.name %></div>
	<%= f.submit "follow", class: "btn btn-primary" %>
<% end %>	

app/views/shared/_picture_form.html.erb
<div class="picture_form">


<script>
  var fileUploadErrors = {
  maxFileSize: 'File is too big',
  minFileSize: 'File is too small',
  acceptFileTypes: 'Filetype not allowed',
  maxNumberOfFiles: 'Max number of files exceeded',
  uploadedBytes: 'Uploaded bytes exceed file size',
  emptyResult: 'Empty file upload result'
  };
</script>
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
  {% $('.table-striped').show(); for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    <td class="preview"><span class="fade"></span></td>
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="title"><label>Blurb: <input name="picture[blurb]"></label></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else if (o.files.valid && !i) { %}
    <td>
      <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    </td>
    <td class="start">{% if (!o.options.autoUpload) { %}
      <button class="btn btn-primary">
        <i class="icon-upload icon-white"></i>
        <span>{%=locale.fileupload.start%}</span>
      </button>
      {% } %}</td>
    {% } else { %}
    <td colspan="2"></td>
    {% } %}
    <td class="cancel">{% if (!i) { %}
      <button class="btn btn-warning">
        <i class="icon-ban-circle icon-white"></i>
        <span>{%=locale.fileupload.cancel%}</span>
      </button>
      {% } %}</td>
  </tr>
  {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        <td colspan="2" id="form_hide" onclick="$(this).closest('tr.template-download').remove();"><button>x</button></td>
      {% } else { %}
        <td class="preview">{% if (file.url) { %}
          <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.url%}"></a>
          {% } %}</td>
        <td class="name">
          Picture uploaded successfully.
        </td>
        <td colspan="2" id="form_hide" onclick="$(this).closest('tr.template-download').remove();"><button>x</button></td>
        {% } %}
    </tr>

    {% }
     %}
</script>

<script type="text/javascript" charset="utf-8">
  $(function () {
      // Initialize the jQuery File Upload widget:
      $('#fileupload').fileupload();
      //
      $('#fileupload').bind('fileuploadsubmit', function (e, data) {
          var inputs = data.context.find(':input');
          data.formData = inputs.serializeArray();
      });

  });
</script>

</div>

app/views/shared/_unfollow.html.erb
<%= form_for(current_user.followed_items.find_by_followable_type_and_followable_id(item.class.name, item.id), html: { method: :delete}, remote: true) do |f| %>
	<div><%= hidden_field_tag :followable_id, item.id %></div>
	<div><%= hidden_field_tag :followable_type, item.class.name %></div>
	<%= f.submit "unfollow", class: "btn" %>
<% end %>	

app/views/shared/_vote_modal.html.erb
<div id='modalbak' onclick="modalhide()"></div>
<div id='modalwin'>
  <div id='modalmsg' class="row">
  	<div class="signup col-xs-5">
		<h2>Sign up</h2>

		<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
		  <%= devise_error_messages! %>

		  <div><%= f.label :username %><br />
		  <%= f.text_field :username, autofocus: true, :class => "form-control", placeholder: "Username (required)" %></div>

		  <div><%= f.label :email, "Email (optional)" %><br />
		  <%= f.email_field :email, :class => "form-control", placeholder: "Email (optional)" %></div>

		  <div><%= f.label :password %> <% if @validatable %><i>(<%= @minimum_password_length %> characters minimum)</i><% end %><br />
		    <%= f.password_field :password, autocomplete: "off", :class => "form-control", placeholder: "Password (required)" %></div>

		  <div><%= f.label :password_confirmation %><br />
		    <%= f.password_field :password_confirmation, autocomplete: "off", :class => "form-control", placeholder: "Password confirmation (required)" %></div><br>

		  <div><%= f.submit "Sign up", :class => "btn btn-primary" %></div>
		<% end %>
  	</div>
  	<div class="signin col-xs-5 col-xs-offset-2">
		<h2>Sign in</h2>

		<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
		  <div><%= f.label :username %><br />
		  <%= f.text_field :username, autofocus: true, :placeholder => "Username", :class => "form-control" %></div>

		  <div><%= f.label :password %><br />
		    <%= f.password_field :password, autocomplete: "off", :class => "form-control", :placeholder => "Password" %></div>

		  <% if devise_mapping.rememberable? -%>
		    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
		  <% end -%>

		  <div><%= f.submit "Sign in", :class => "btn btn-primary" %></div>
		<% end %>
  	</div>
  </div>
</div>