config/routes.rb
Pykture::Application.routes.draw do
  devise_for :users
  resources :users, :only => [:show] do
    member do
      get :following, :followers
    end
  end
  resources :pictures, :only => [:index, :destroy, :create]
  resources :followed
  resources :tags, :only => [:show]
  resources :votes, :only => [:create]
  root 'pictures#index'
  get '/index', to: 'pictures#index'
  get '/about', to: 'static_pages#about'
  get '/blog', to: 'static_pages#blog'
  get '/legal', to: 'static_pages#legal'
  get '/search', to: 'search#search'
  resources :relationships, only: [:create, :destroy]

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :pictures_tags
	has_many :pictures, through: :pictures_tags
  has_many :followers, class_name: "Relationship", :as => :followable

  def self.top_five
    Tag.select("tags.*, count(relationships.followable_id) as count").joins(:followers).group("tags.id").order("count DESC").limit(5)
  end

  def to_param
    name
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find_by_name(params[:id])
    @filter = params.fetch(:filter, ["hot"])
    @pictures = @tag.pictures.filter(@filter).paginate(:per_page => 20, :page => params[:page])
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_follow_form.html.erb
<% if current_user.following?(item) %>
	<%= render 'shared/unfollow', :item => item %>
<% else %>	
	<%= render 'shared/follow', :item => item %>
<% end %>

app/views/tags/show.html.erb
<%= render 'shared/picture_form' %>

<div class="top_wrap clearfix row container">

	<div class="tag_show col-md-4">
		<h2><%= @tag.name %></h2>

		<div id="follow">
			<%= render "follow_form", :item => @tag if current_user %>
		</div>
	</div>

	<div class="col-md-3">
		<div class="follow">
			<div class="following">
				<p><%= @tag.followers.count %> followers</p>
			</div>
		</div>
	</div>
		
	<div class="sort_by col-md-3 col-md-offset-2">
		<ul>
			<li id="<%= @filter[0] == 'hot' ? 'selected' : '' %>">
				<%= link_to "hot", tag_path(:filter => ["hot"]) %>
			</li>
			<li id="<%= @filter[0] == 'recent' ? 'selected' : '' %>">
				<%= link_to "recent", tag_path(:filter => ["recent"]) %>
			</li>
		</ul>
	</div>

</div>	

<div class="pictures">
	<% @pictures.each do |picture| %>
		<%= render 'pictures/picture', :picture => picture %>
	<% end %>
</div>