config/routes.rb
Pykture::Application.routes.draw do
  devise_for :users
  resources :users, :only => [:show] do
    member do
      get :following, :followers
    end
  end
  resources :pictures, :only => [:index, :destroy, :create]
  resources :followed
  resources :tags, :only => [:show]
  resources :votes, :only => [:create]
  root 'pictures#index'
  get '/index', to: 'pictures#index'
  get '/about', to: 'static_pages#about'
  get '/blog', to: 'static_pages#blog'
  get '/legal', to: 'static_pages#legal'
  get '/search', to: 'search#search'
  resources :relationships, only: [:create, :destroy]

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  before_save :create_tags
  mount_uploader :picture, PictureUploader

  has_many :pictures_tags, :dependent => :destroy
  has_many :tags, through: :pictures_tags 

  has_many :votes, :dependent => :destroy
  belongs_to :user
  validates :picture, :presence => true
  require 'will_paginate/array'

  scope :filter, lambda { |params|
    case params[0]
      when "hot"
        includes(:tags, :user, :votes)
        .sort_by(&:hot_number)
        .reverse!
      when "recent"
        order('created_at DESC')
        .includes(:tags, :user, :votes)
      when "popular"
        if %w(day hour month year).include?(params[1])
          where('created_at > ?', 1.send(params[1]).ago)
        else
          all
        end
        .order('number_of_votes DESC, number_of_upvotes DESC')
        .includes(:tags, :user, :votes)
      when "liked"
        if %w(day hour month year).include?(params[1])
          where('created_at > ?', 1.send(params[1]).ago)
        else
          all
        end
        .order('number_of_upvotes DESC, number_of_votes ASC')
        .includes(:tags, :user, :votes)
      else # also HOT
        includes(:tags, :user, :votes)
        .sort_by(&:hot_number)
        .reverse!
      end
    } 
  # ------------
  # Filters
  #-------------

  def self.followed_by(user)
    Picture.joins(:pictures_tags)
    .where('pictures.user_id IN (?) OR pictures_tags.tag_id IN (?)', user.followed_users_ids, user.followed_tags_ids )
    .uniq
  end

  # ------------
  # Voting
  #-------------

  def vote(direction, user_id)
    if direction
      self.number_of_votes += 1
      self.number_of_upvotes += 1
      self.votes.create(:user_id => user_id,
              :picture_id => self.id,
              :up => true)
      self.save
    else
      self.number_of_votes += 1
      self.votes.create(:user_id => user_id,
              :picture_id => self.id,
              :up => false)
      self.save
    end 
    return self
  end

  def change_vote(vote, previous_direction, new_direction)
    if previous_direction == new_direction
      return self
    elsif new_direction == true
      vote.up = true
      self.number_of_upvotes += 1
    else
      vote.up = false
      self.number_of_upvotes -= 1
    end
    vote.save
    self.save
    return self
  end
  

  def up_votes
    # return self.votes.where('up like ?', true).count.to_f
    return self.number_of_upvotes
  end

  def self.get_background_pic
    where('created_at > ?', 1.day.ago).order('number_of_upvotes DESC, number_of_votes ASC').sample.presence || last
  end

  def hot_number
    return (up_votes - 1) / (hours_ago + 2)**1.5
  end

  def hours_ago
    ((Time.now - created_at)/60/60)
  end

  # ------------
  # Tagging
  #-------------

  def self.tagged_with(name)
    Tag.find_by_name!(name).pictures
  end

  def self.tag_counts
  Tag.select("tags.*, count(pictures_tags.tag_id) as count").joins(:pictures_tags).group("tags.id").order("count DESC").limit(10)
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

  include Rails.application.routes.url_helpers

  def to_jq_upload
    {
      "name" => self.blurb,
      "size" => self.picture.size,
      "url" => self.picture.url,
      "delete_url" => picture_path(self),
      "delete_type" => "DELETE"
    }
  end

  private

  # Adds existing tags to Picture or creates new Tags if they dont exist
  def create_tags
    hashtag_regex = /\B#\w\w+/
    tags = self.blurb.scan(hashtag_regex)
    tags.each do |tag|
      to_add = Tag.where(:name => tag).first_or_create!
      self.tags << to_add unless self.tags.include?(to_add)
    end
  end




end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def index
    if confirm_params_or_redirect(params)
      redirect_to root_path(:filter => session[:filter]) and return
    end
    @pictures = Picture.filter(params.fetch(:filter, "hot")).paginate(:per_page => 20, :page => params[:page])
    @view = "all"
  end

  def create
    @picture = Picture.create(picture_params)

    respond_to do |format|
      if @picture.save
        format.html {
          render :json => [@picture.to_jq_upload].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json { render json: {files: [@picture.to_jq_upload]}, status: :created, location: @upload }
      else
        format.html { render "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    if @picture.user = current_user
      @picture.destroy
    end
    @failed = Picture.exists?(@picture)
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end



  

  private

    def picture_params
      params.require(:picture).permit(:picture, :blurb).merge(:user_id => current_user.id)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper

	def with_links(picture)
		blurb = picture.blurb
		picture.tags.each do |tag|
			blurb = blurb.sub tag.name, link_to(tag.name, tag_path(tag.name))
		end
		raw blurb
	end
end

app/views/pictures/_all_or_followed.html.erb
<ul>
	<li id="<%= view == 'all' ? 'selected' : '' %>">
		<%= link_to "all", root_path %>
	</li>
	<% if current_user %>
	<li id="<%= view == 'followed' ? 'selected' : '' %>">
		<%= link_to "followed", followed_index_path %>
	</li>
	<% end %>
</ul>

app/views/pictures/_downvote.html.erb
<%= link_to raw('<i class="fa fa-arrow-up"></i>'), votes_path(:vote => {:picture_id => picture.id, :up => 1}), :method => :post, :class => "upvote", remote: true %>
<%= link_to raw('<i class="fa fa-arrow-down selected"></i>'), votes_path(:vote => {:picture_id => picture.id, :up => 0}), :method => :post, :class => "downvote", remote: true %>

app/views/pictures/_novote.html.erb
<%= link_to raw('<i class="fa fa-arrow-up"></i>'), votes_path(:vote => {:picture_id => picture.id, :up => 1}), :method => :post, :class => "upvote", remote: true %>
<%= link_to raw('<i class="fa fa-arrow-down"></i>'), votes_path(:vote => {:picture_id => picture.id, :up => 0}), :method => :post, :class => "downvote", remote: true %>

app/views/pictures/_picture.html.erb
<div class="single_picture" data-rel="groupA" id="picture_<%= picture.id %>">
	<a href="<%= picture.picture.url %>" id="full_size" alt='<%= with_links(picture) %>'><%= image_tag picture.picture.url(:small) %></a>
	<div class="pop" href="<%= picture.picture.url %>">
		<div class="row">
			<div class="voters pic_<%= picture.id %> col-md-3">
				<% if current_user %>
					<% if current_user.voted_on?(picture) == true %>
						<%= render 'pictures/upvote', :picture => picture %>
					<% elsif current_user.voted_on?(picture) == false %>	
						<%= render 'pictures/downvote', :picture => picture %>
					<% else %>
						<%= render 'pictures/novote', :picture => picture %>
					<% end %>
				<% else %>
					<i class="fa fa-arrow-up" onclick="modalshow()"></i>
					<i class="fa fa-arrow-down" onclick="modalshow()"></i>	
				<% end %>	

			</div>
			<div class="username info col-md-8">
				<p class="username">	
					<% if picture.user %>
						<%= link_to picture.user.username, user_path(picture.user.username) %>
					<% else %>
						[deleted]
					<% end %>		
				</p>
			</div>
		</div>

		<% unless picture.blurb.empty? %>
			<div class="row">
				<div class="title info">
					<p class="title">
						<%= with_links(picture) %>
					</p>	
				</div>
			</div>
		<% end %>	
		
		<% if current_user and current_user == picture.user %>
			<div class="row delete">
				<p>
					<%= link_to "delete", picture_path(picture), :method => :delete, class: "btn btn-danger btn-xs delete-confirm", :remote => true, data: { confirm: 'Delete?' } %>
				</p>
			</div>
		<% end %>
	</div>
</div>

app/views/pictures/_sort_by.html.erb
<!-- <div class="sort_wrap"> -->
<!-- <div class="sb_wrap"> -->
	<ul>
		<li id="<%= filter[0] == 'hot' ? 'selected' : '' %>">
			<%= link_to "hot", url_for(:action => "index", :filter => ["hot"]) %>
		</li>
		<li id="<%= filter[0] == 'recent' ? 'selected' : '' %>">
			<%= link_to "recent", url_for(:action => "index", :filter => ["recent"]) %>
		</li>
		<li id="<%= filter[0] == 'popular' ? 'selected' : '' %>">
			<%= link_to "most popular", url_for(:action => "index", :filter => ["popular","day"]) %>
		</li>
		<li id="<%= filter[0] == 'liked' ? 'selected' : '' %>">
			<%= link_to "most liked", url_for(:action => "index", :filter => ["liked","day"]) %>
		</li>
	</ul>
<!-- </div> -->
<!-- <div class="sb_wrap"> -->
	<% if filter[0] == "popular" || filter[0] == "liked" %>
		<ul class="date">
			<li id="<%= filter[1] == 'day' ? 'selected' : '' %>">
				<%= link_to "today", url_for(:action => "index", :filter => [filter[0], "day"]) %>
			</li>
			<li id="<%= filter[1] == 'hour' ? 'selected' : '' %>">
				<%= link_to "hour", url_for(:action => "index", :filter => [filter[0], "hour"]) %>
			</li>
			<li id="<%= filter[1] == 'month' ? 'selected' : '' %>">
				<%= link_to "month", url_for(:action => "index", :filter => [filter[0], "month"]) %>
			</li>
			<li id="<%= filter[1] == 'all' ? 'selected' : '' %>">
				<%= link_to "all time", url_for(:action => "index", :filter => [filter[0], "all"]) %>
			</li>
		</ul>
	<% end %>
<!-- </div>	 -->
<!-- </div> -->

app/views/pictures/_tag_cloud.html.erb
<div class="tag_cloud">
	<% tag_cloud Picture.tag_counts, %w[s sm m ml l] do |tag, css_class| %>
		<%= link_to tag.name, tag_path(tag), class: css_class %>
	<% end %>	
</div>

app/views/pictures/_top_tags.html.erb
<div class="col-md-4">
	<h2>Tags</h2>
	<div class="tag_cloud">
		<% tag_cloud Tag.top_five, %w[s sm m ml l] do |tag, css_class| %>
			<%= link_to tag.name, tag_path(tag), class: css_class %>
		<% end %>
	</div>
</div>

		

app/views/pictures/_top_users.html.erb
<div class="col-md-4 col-md-offset-2">
	<h2>Users</h2>
	<div class="tag_cloud">
		<% tag_cloud User.top_five, %w[s sm m ml l] do |user, css_class| %>
			<%= link_to user.username, user_path(user), class: css_class %>
		<% end %>
	</div>
</div>

app/views/pictures/_upvote.html.erb
<%= link_to raw('<i class="fa fa-arrow-up selected"></i>'), votes_path(:vote => {:picture_id => picture.id, :up => 1}), :method => :post, :class => "upvote", remote: true %>
<%= link_to raw('<i class="fa fa-arrow-down"></i>'), votes_path(:vote => {:picture_id => picture.id, :up => 0}), :method => :post, :class => "downvote", remote: true %>

app/views/pictures/create.js.erb
<%# if @picture.new_record? %>
	$('.picture_form').prepend("Upload failed. <%= j @picture.errors.full_messages.join(" ") %>")
<%# else %>
	$('.picture_form').prepend("Picture saved.")
<%# end %>

$('.picture_form').prepend('<%=  @picture %>')

app/views/pictures/destroy.js.erb
<% unless @failed %>
	$('#picture_<%= @picture.id %>').slideUp()
<% end %>	
	

app/views/pictures/index.html.erb
<%= render 'shared/picture_form' %>

<div class="top_wrap row container">

	<div class="view_show col-md-2">
		<%= render "pictures/all_or_followed", :view => @view %>
	</div>

	<div class="col-md-5">
		<%= render "tag_cloud" if @view == "all" %>
		<%= render "followed/followed" if @view == "followed" %>
	</div>

	<div class="sort_by col-md-5">
		<%= render 'pictures/sort_by', :filter => params[:filter] %>
	</div>


</div>	

<% if @pictures.any? %>
	<div class="pictures">
		<% @pictures.each do |picture| %>
			<%= render 'pictures/picture', :picture => picture %>
		<% end %>
	<br><%= will_paginate @pictures %>
	</div>
<% elsif @view == "followed" %>	
	
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h2>You're not following any pages yet.</h2>
			<h3>People seem to like these pages.</h3>
		</div>
	</div>

	<div class="row">
		<%= render 'pictures/top_users' %>
		<%= render 'pictures/top_tags' %>
	</div>

<% end %>