config/routes.rb
Pykture::Application.routes.draw do
  devise_for :users
  resources :users, :only => [:show] do
    member do
      get :following, :followers
    end
  end
  resources :pictures, :only => [:index, :destroy, :create]
  resources :followed
  resources :tags, :only => [:show]
  resources :votes, :only => [:create]
  root 'pictures#index'
  get '/index', to: 'pictures#index'
  get '/about', to: 'static_pages#about'
  get '/blog', to: 'static_pages#blog'
  get '/legal', to: 'static_pages#legal'
  get '/search', to: 'search#search'
  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default navbar-static-top footer" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<%= link_to image_tag("pykture.png", :id => "footer"), root_path, :class => "navbar-brand", :id => "logo" %>
	    </div>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%# link_to "about", about_path %></li>
        <li><%# link_to "blog", blog_path %></li>
        <li><%# link_to "legal", legal_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div><!-- /.navbar-collapse -->
	</div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<%= link_to image_tag("pykture.png", :id => "header"), root_path, :class => "navbar-brand", :id => "logo" %>
	    </div>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<% if current_user %>
        <li>
          <%= form_for Picture.new, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
          <div class="row fileupload-buttonbar">
            <div class="span7">
              <!-- The fileinput-button span is used to style the file input field as button -->
              <span class="btn btn-success fileinput-button">
                <i class="icon-plus icon-white"></i>
                <span>upload</span>
                <%= f.file_field :picture, multiple: true, name: "picture[picture]" %>
              </span>
            </div>
            <div class="span5">
              <!-- The global progress bar -->
              <div class="progress progress-success progress-striped active fade">
                <div class="bar" style="width:0%;"></div>
              </div>
            </div>
          </div>
          <!-- The loading indicator is shown during image processing -->
          <div class="fileupload-loading"></div>
          <br>
          <!-- The table listing the files available for upload/download -->
          <table class="table table-striped">
            <tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
          </table>
        <% end %> <!-- form end -->
      </li>
        <% else %>
	        <li><%= link_to 'sign in', new_user_session_path %></li>
          <li><%= link_to 'sign up', new_user_registration_path %></li>
      	<% end %>
      </ul>

      <!-- search -->
      <div class="col-sm-3 col-md-3 pull-right">
        <form class="navbar-form" role="search" action="<%= search_url %>">
          <div class="input-group searcher">
              <input type="text" class="form-control typeahead" data-provide="typeahead" placeholder="Search" name="srch-term" id="search-term" autocomplete="off">
              <div class="input-group-btn">
                  <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
              </div>
          </div>
        </form>
      </div>

      <ul class="nav navbar-nav navbar-right">
      	<% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
          	Hi <%= current_user.username %>
          <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "my pictures", user_path(current_user.username)%></li>
            <li class="divider"></li>
            <li><%= link_to 'sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      	<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="icon" type="image/png" href='<%= image_path("pykture_solo.png") %>'>
  <title>pykture</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>">
		<a href="#" data-dismiss="alert" class="close">x</a>
			<ul>
				<li>
					<%= value %>
				</li>
			</ul>
	</div>
	<script type="text/javascript">
	$(document).ready(function(){
	  setTimeout(function(){
	    $('.alert').slideUp();
	  }, 2500);
	 })
	</script>
<% end %>

<%= render 'layouts/header' %>
<div class="layer">
	<%= yield %>
<div class="push"></div>
</div>
<%= render 'layouts/footer' %>
<%# debug(params) if Rails.env.development? %>
<%= javascript_tag do %>
	window.background_picture = <%= raw(@background_picture.to_json) %>
<% end %>
<%= render 'shared/vote_modal' %>
</body>
</html>